name: Deploy Github Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup LTS Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Lock abbrlink
      run: node ./lock_abbrlink.js

    - name: Build
      run: |
        npx hexo clean
        npx hexo generate

    - name: Check if there are changes
      id: diff
      run: git diff --quiet
      continue-on-error: true

    - name: Commit changes
      if: ${{ steps.diff.outcome == 'failure' }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "Lock abbrlink after ${{ github.event.after }}"
        git push

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
